config/routes.rb
Phonein::Application.routes.draw do

  resources :clients do
    resources :tasks
  end

  resources :agents
  
  resources :twilios do
    collection do
      post 'incoming'
      post 'verify'
      post 'direction'
    end
  end

  devise_for :admins

  root :to => 'home#index'

  match ':controller(/:action(.:format))'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :clients
  has_many :agents
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  belongs_to :admin
  has_many :pairs
  
  validates :code, :uniqueness => true,  
                   :numericality => { :only_integer => true },
                   :length => { :is => 6, :message => "must be six-digits." }  
  
  def check_in(cid)
    self.pairs.create(:client_id => cid, :state => "checked_in")
  end
  
  def check_out(cid)
    self.pairs.create(:client_id => cid, :state => "not_checked_in")
  end
  
  def checked_in?(cid)
    if self.pairs.last 
      self.pairs.last.client_id == cid.to_i && self.pairs.last.state == "checked_in"
    else
      nil
    end
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  has_many :pairs
  belongs_to :admin
  
  before_validation do
    self.phone = self.phone.gsub(/\D/, '')
  end
      
  validates :phone, :uniqueness => true, 
                    :length => { :is => 10, :message => "needs to be a correct US phone number" }
                        
  def task_list
    tasks = self.tasks
    task_list = "There are #{tasks.size} tasks to perform today."
    if tasks.size > 0
      tasks.each_with_index do |task, index|
        task_list << "Task #{index+1}, #{task.name}. "
      end
    end
    task_list
  end
  
  def agent
    if self.pairs.last.state == "checked_in"
      Agent.find(self.pairs.last.agent_id)
    else
      nil
    end
  end
  
  def agents
    self.pairs.order("created_at DESC")
  end
end

app/models/pair.rb
class Pair < ActiveRecord::Base
  belongs_to :client
  belongs_to :agent
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :client
  
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController  
  def index
    @agents = current_admin.agents.all
  end

  def show
    @agent = current_admin.agents.find(params[:id])
  end

  def new
    @agent = current_admin.agents.new
  end

  def edit
    @agent = current_admin.agents.find(params[:id])
  end

  def create    
    @agent = current_admin.agents.new(params[:agent])

    if @agent.save
      redirect_to @agent, :notice => 'Agent was successfully created.'
    else
      render :action => "new", :alert => 'Failed to create an agent.'
    end
  end

  def update
    @agent = current_admin.agents.find(params[:id])

    if @agent.update_attributes(params[:agent])
      redirect_to @agent, :notice => 'Agent was successfully updated.'
    else
      render :action => "edit", :alert => 'Failed to update the agent.'
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent = current_admin.agents.find(params[:id])
    @agent.destroy

    redirect_to agents_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_admin! 
  
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
 
  def index
    @clients = current_admin.clients.all
  end

  def show
    @client = current_admin.clients.find(params[:id])
  end

  def new
    @client = current_admin.clients.new
  end

  def edit
    @client = current_admin.clients.find(params[:id])
  end

  def create
    @client = current_admin.clients.new(params[:client])

    if @client.save
      redirect_to @client, :notice => 'Client was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @client = current_admin.clients.find(params[:id])

    if @client.update_attributes(params[:client])
      redirect_to @client, :notice => 'Client was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @client = current_admin.clients.find(params[:id])
    @client.destroy

    redirect_to clients_url
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_admin! 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_filter :client

  def index
    @tasks = @client.tasks.all
  end

  def show
    @task = @client.tasks.find(params[:id])
  end

  def new
    @task = @client.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @task = @client.tasks.find(params[:id])
  end

  def create
    @task = @client.tasks.new(params[:task])

    if @task.save
      redirect_to client_tasks_path(@client), :notice => 'Task was successfully created.'
    else
      render :action => 'new', :alert => 'Task not added!'
    end
  end

  def update
    @task = @client.tasks.find(params[:id])

    if @task.update_attributes(params[:task])
      redirect_to client_tasks_path(@client), :notice => 'Task was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @task = @client.tasks.find(params[:id])
    @task.destroy

    redirect_to @client.tasks_path(@client)
  end

  protected
  
  def client
    @client = Client.find(params[:client_id])
  end
end

app/controllers/twilios_controller.rb
class TwiliosController < ApplicationController
  
  skip_before_filter :authenticate_admin! 
  
  BASE_URL = "http://phonein.herokuapp.com/twilios"
  
  def incoming
    # Get client by phone number
    client_phone = params['From'][2..params['From'].size]
    @client = Client.find_by_phone(client_phone)
    
    # Welcom message.
    # "Welcome to #{@client.name}'s residence."
    # Ask agent to identy him/herself.
    # "Please enter your code"
    if @client.nil? 
      render :action => "no_client.xml.builder"
    else
      @post_to = BASE_URL + "/verify?client_id=#{@client.id}"
      render :action => "incoming.xml.builder", :layout => false
    end
  end
  
  def verify
    @client = Client.find(params[:client_id])    
    @agent = Agent.find_by_code(params['Digits'])
    
    if @agent.nil?
      @post_to = BASE_URL + "/verify?client_id=#{@client.id}"
      render :action => "no_agent.xml.builder"
      return
    else
      if @agent.checked_in?(@client.id) 
        @message = "You have already checked in."
      else
        @agent.check_in(@client.id)
        @message = "Now you are checked in."
      end
    end 

    @post_to = BASE_URL + "/direction?agent_id=#{@agent.id}&client_id=#{@client.id}"
    render :action => "direction.xml.builder", :layout => false
  end
        
  def direction    
    @client = Client.find(params[:client_id])
    @agent = Agent.find(params[:agent_id])
    @message = @client.task_list
    @post_to = BASE_URL + "/direction?agent_id=#{@agent.id}&client_id=#{@client.id}"
    
    # 1 to hear the tasks again, 2 to check out, 3 to hang up.
    if params['Digits'] == '1'
      render :action => "direction.xml.builder", :layout => false
    elsif params['Digits'] == '2'
      @agent.check_out(@client.id)
      @goodbye_message = "Thank you for your service today."
      render :action => 'goodbye.xml.builder', :layout => false
    elsif params['Digits'] == '3'
      @message = "Yang is the most awesome guy ever - both personally and professionally. He is pretty sexy, too."
      render :action => 'direction.xml.builder', :layout => false
    elsif params['Digits'] == '4'
      @goodbye_message = "Have a great day."
      render :action => 'goodbye.xml.builder', :layout => false
    end
  end
    
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/twilios_helper.rb
module TwiliosHelper
end

app/views/agents/_form.html.erb
<%= form_for @agent, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Agent</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :code, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :code, :maxlength => 6, :class => 'text_field', :placeholder => 'Enter a six-digit code' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary btn-large' %>
      <%= link_to 'Cancel', agents_path, :class => 'btn btn-large' %>
    </div>
  </fieldset>
<% end %>

app/views/agents/edit.html.erb
<%= render :partial => 'form' %>

app/views/agents/index.html.erb
<h1>Agents</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.id %></td>
        <td><%= link_to agent.name, agent_path(agent) %></td>
        <td><%= agent.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_agent_path(agent), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', agent_path(agent), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_agent_path, :class => 'btn btn-primary' %>

app/views/agents/new.html.erb
<%= render :partial => 'form' %>

app/views/agents/show.html.erb
<h1>Agent</h1>

<p>
  <b>Name</b><br>
  <%= @agent.name %>
</p>

<p>
  <b>Code</b><br>
  <%= @agent.code %>
</p>

<div class="form-actions">
  <%= link_to 'Back', agents_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_agent_path(@agent), :class => 'btn' %>
  <%= link_to 'Delete', agent_path(@agent), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/clients/_agents.html.erb
<tr>
  <td><%= link_to pair.agent.name, agent_path(pair.agent) %></td>
  <td>
    <% if pair.state == "checked_in" %>
      <%= pair.created_at.localtime %>
    <% else %>
      N/A
    <% end %>
  </td>
  <td>
    <% if pair.state == "not_checked_in" %>
      <%= pair.created_at.localtime %>
    <% else %>
      N/A
    <% end %>
  </td>
</tr>

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Client</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :phone, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :phone, :class => 'text_field', :maxlength => 12, :placeholder => '"1112223333" or "111-222-3333"' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', clients_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/clients/edit.html.erb
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<h1>Clients</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.id %></td>
        <td><%= link_to client.name, client_path(client) %></td>
        <td><%= client.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_client_path(client), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', client_path(client), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_client_path, :class => 'btn btn-primary' %>

app/views/clients/new.html.erb
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<h1>Client</h1>

<div class="row">
  <div class="span6">
    <p>
      <b>Name</b><br>
      <%= @client.name %>
    </p>

    <p>
      <b>Phone</b><br>
      <%= @client.phone %>
    </p>
    
  </div>

  <div class="span6">
    <h3>Tasks</h3>
    <ul>
      <%= render @client.tasks %>
    </ul>
    <%= link_to "Add or Edit a task", client_tasks_path(@client) %>
  </div>
  
  <div class="span12">
    <div class="form-actions">
      <%= link_to 'Back', clients_path, :class => 'btn'  %>
      <%= link_to 'Edit', edit_client_path(@client), :class => 'btn' %>
      <%= link_to 'Delete', client_path(@client), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
    </div>
  </div>
</div>

<h3>Agent history</h3>
<p>
  <% if @client.agents.size > 0 %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Agent Name</th>
          <th>Checked-In Time</th>
          <th>Checked-Out Time</th>
        </tr>
      </thead>
      <tbody>
          <%= render :partial => 'agents', :collection => @client.agents, :as => :pair %>
      </tbody>
    </table>  
  <% else %>
    There is no history of an agent having checked in for this client.
  <% end %>
</p>

app/views/home/index.html.erb
<div class="row">
  <div class="hero-unit span12">
    <h1>Phone In</h1>
    <% if admin_signed_in? %>
      <p>Welcome back, <%= current_admin.email %></p>
      <div class="row">
        <div class="span4">
          <%= link_to "Manage Clients", clients_path, :class => "btn btn-primary btn-large"%>
        </div>
        <div class="span4">
          <%= link_to "Manage Agents", agents_path, :class => "btn btn-primary btn-large"%>
        </div>
        <div class="span4">
          <%= link_to "Buy a Phone Number", "#", :class => "btn btn-primary btn-large disabled"%>
          <p><em>Coming Soon!</em></p>
        </div>
      </div>
    <% else %>
      <p>Running an in-home care business?</p> 
      <p>Do you need to ensure your employee's arrival and departure at a client's residence?</p> 
      <p><strong>Have in-home care professional check in and out by making a phone call and following SIMPLE directions.</strong></p>
      <p><%= link_to "Sign-up Today!", new_admin_registration_path, :class => "btn btn-primary btn-large"%></p>
    <% end %>
 </div>
  <% if !admin_signed_in? %>
    <div class="span4">
      <h1>Step 1</h1>
      <h3>Create a client and tasks</h3>
    </div>
    <div class="span4">
      <h1>Step 2</h1>
      <h3>Create an agent</h3>
    </div>
    <div class="span4">
      <h1>Step 3</h1>
      <h3>Have an agent check in and out using client's phone</h3>
    </div>
  <% end %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonein</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Phone In", root_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Clients", clients_path %></li>
            <li><%= link_to "Agents", agents_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li>
              <% if admin_signed_in? %>
                <%= link_to "Sign Out", destroy_admin_session_path, :method => "delete" %>
              <% else %>
                <%= link_to "Sign In", new_admin_session_path %>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <a class="close" data-dismiss="alert">×</a>
        <strong><%= notice %></strong>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <strong><%= alert %></strong>
      </div>
    <% end %>
    
    <% if admin_signed_in? %>
      <div class="row">
        <div class="span12">
          <p>Test Number: <strong>+1-415-599-2671</strong>, PIN: <strong>3622-9670</strong></p>
        </div>
      </div>
    <% end %>
   
    <p><%= content_for?(:content) ? yield(:content) : yield %> </p>

    <hr>

    <footer>
      <p>&copy; Yang Chung 2012</p>
    </footer>
  </div>
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-10418051-6']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>

app/views/layouts/devise.html.erb
<% content_for :content do %>
<div class="devise">
	<%= yield %>
</div>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/tasks/_form.html.erb
<%= form_for [:client, @task], :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Task</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', client_tasks_path(@client), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/tasks/_task.html.erb
<li><%= task.name %></li>

app/views/tasks/edit.html.erb
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks for <%= @client.name %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.name %></td>
        <td><%= task.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_client_task_path(@client, task), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', client_task_path(@client, task), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_client_task_path, :class => 'btn btn-primary' %>
<%= link_to 'Back to Client', client_path(@client), :class => 'btn' %>

app/views/tasks/new.html.erb
<%= render :partial => 'form' %>